### ISSUE TITLE
$time not being initialised?

### ISSUE THREAD

**Issue by Ashfaak** [rtts/photog-perl#1]
I sometimes get this error:

Use of uninitialized value $time in concatenation (.) or string at /usr/local/share/perl/5.18.2/Photography/Website.pm line 401.

It seems to be initialised on line 399, so I'm not sure what's going on.

**Comment by JaapJoris** [comment]
Unfortunately I'm abandoning this project in favor of a much simper rewrite in Python which you can checkout here: https://github.com/rtts/photog-python

Thanks for your support!
