### ISSUE TITLE
sort option: by filename

### ISSUE THREAD

**Issue by macau23** [rtts/photog-perl#4]
I have some images which do not have EXIF data, and sometimes I rename photos to fix the ordering. An option to sort by filename could be nice.

**Comment by Geocacher** [comment]
I have the same issue in that I scan old slides and the scanner software puts in the scan date and time, not a time that I can use to sequence the images. I agree with macau23 that the option to sort by filename (ASCII sort order of the filename, not including extension) would be really handy.

**Comment by macau23** [comment]
@konrul has taken my sorting patch and is running a fork of photog at https://github.com/konrul/photog

I'm going to submit patches there from now on.

**Comment by Geocacher** [comment]
Thank you for taking the time to let me know.

Regards;
Gary Gauthier
