### ISSUE TITLE
This project is amazing

### ISSUE THREAD

**Issue by macau23** [rtts/photog-perl#5]
Hi.

This project is *amazing*. It's exactly what I was looking for: a cli tool for generating static galleries. THANKS for writing this. I would be happy to contribute if I can. We need to get more people looking at it!

**Comment by Geocacher** [comment]
This is BY FAR the best website generator I've seen. I know that the folks at PhotoMechanic would love to know about this. They cannot handle nested directories and reflect those in their generated website. In fact they once stated in their forums that they knew of no such tool.

**Comment by JaapJoris** [comment]
Thanks for your support!
