### ISSUE TITLE
Picture Processing Loop Index Issue

### ISSUE THREAD

**Issue by Geocacher** [rtts/photog-perl#6]
When I run the version of the software offered via the authors webpage, I get the following error message at the end of the processing of every directory of photos. I've seen this type of thing before when a loop index is incremented to point to a non-existant item. The code still works, though, so it's not a severe issue.

/Roll 014/Europe_R014_F019.jpg
convert: geometry does not contain image `red' @ warning/transform.c/ShaveImage/1630.
/Roll 014/index.html
/Roll 015/Europe_R015_F-001.jpg

**Comment by JaapJoris** [comment]
This message is produced by ImageMagick for unknown reasons. The Python version of Photog! has ditched ImageMagick in favor of Pillow: https://github.com/rtts/photog-python
