### ISSUE TITLE
Potential Issue with the generation of "all.jpg"

### ISSUE THREAD

**Issue by Geocacher** [rtts/photog-perl#7]
When the software is run, the instances of "all.jpg" are all blank JPGs, even for directories that have more than enough JPG images to create the composite "all.jpg". No errors about the formation of the "all.jpg" are shown during generation.

**Comment by JaapJoris** [comment]
Unfortunately I'm abandoning this project in favor of a much simper rewrite in Python which you can checkout here: https://github.com/rtts/photog-python

Thanks for your support!
