### ISSUE TITLE
Suggested Feature: Allow specified IPTC Fields to be displayed below images

### ISSUE THREAD

**Issue by Geocacher** [rtts/photog-perl#8]
Forgive me if I've missed this capability in the existing software, but it would really improve the usefulness of Photog if one could display at least one selected IPTC field below an Image. The ideal solution would be to show the Headline and Title/Caption fields from the embedded IPTC metadata.

**Comment by JaapJoris** [comment]
Unfortunately I'm abandoning this project in favor of a much simper rewrite in Python which you can checkout here: https://github.com/rtts/photog-python

Thanks for your support!
